// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"business/internal/biz"
	"business/internal/conf"
	"business/internal/data"
	"business/internal/server"
	"business/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	registrar := server.NewRegistrar(registry)
	discovery := data.NewDiscovery(registry)
	reviewClient := data.NewReviewServiceClient(discovery)
	dataData, cleanup, err := data.NewData(reviewClient, logger)
	if err != nil {
		return nil, nil, err
	}
	businessRepo := data.NewBusinessRepo(dataData, logger)
	businessUsecase := biz.NewBusinessUsecase(logger, businessRepo)
	businessService := service.NewBusinessService(businessUsecase)
	grpcServer := server.NewGRPCServer(confServer, businessService, logger)
	httpServer := server.NewHTTPServer(confServer, businessService, logger)
	app := newApp(logger, registrar, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
